### Intentar iniciar sesión (Login Real)
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "nombre_usuario": "admin",
    "contrasena": "admin123",
    "nombre_completo": "Administrador Principal",
    "rol": "admin",
    "correo": "admin123@gmail.com"

}